---
apiVersion: batch/v1
kind: Job
metadata:
  name: prometheus-generate-data
spec:
  selector: {}
  template:
    metadata:
      name: pi
    spec:
      containers:
        - name: "prometheus-generate-data"
          command: ["/bin/sh"]
          args: ["-c", "go get -u github.com/jjneely/stuff/cmd/historygen; cd ~/go/src/github.com/jjneely/stuff/cmd/historygen; go build; ./historygen -c 10 -o /data"]
          image: "golang:1.13.8"
          imagePullPolicy: IfNotPresent
          env:
            - name: XDG_CACHE_HOME
              value: "/tmp/.cache"
          volumeMounts:
            - mountPath: /etc/prometheus
              name: prometheus-config
            - mountPath: /data
              name: prometheus-data
      restartPolicy: Never
      volumes:
        - name: prometheus-config
          configMap:
            defaultMode: 420
            name: "{{ prometheus_app_name }}"
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: "{{ prometheus_app_name }}"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: "{{ prometheus_app_name }}"
  name: "{{ prometheus_app_name }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ prometheus_pvc_capacity }}"
