---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: "{{ prometheus_app_name }}"
  labels:
    deploymentConfig: "{{ prometheus_app_name }}"
    app: "{{ prometheus_app_name }}"
spec:
  replicas: 1
  selector:
    deploymentConfig: "{{ prometheus_app_name }}"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deploymentConfig: "{{ prometheus_app_name }}"
        app: "{{ prometheus_app_name }}"
    spec:
      containers:
        - name: "{{ prometheus_app_name }}"
          args:
            - --storage.tsdb.path=/data
            - --storage.tsdb.retention.time={{ prometheus_tsdb_retention_time }}
            - --storage.tsdb.min-block-duration=2h
            - --storage.tsdb.max-block-duration=2h
            - --config.file=/etc/prometheus/prometheus.yml
            - --web.listen-address=0.0.0.0:9090
          image: "{{ prometheus_container_image }}"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: '1'
              memory: "{{ prometheus_container_memory_limit }}"
          volumeMounts:
            - mountPath: /etc/prometheus
              name: prometheus-config
            - mountPath: /data
              name: prometheus-data
      restartPolicy: Always
      volumes:
        - name: prometheus-config
          configMap:
            defaultMode: 420
            name: "{{ prometheus_app_name }}"
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: "{{ prometheus_app_name }}"

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ prometheus_app_name }}"
  labels:
    app: "{{ prometheus_app_name }}"
spec:
  ports:
    - port: 9090
      name: http
  selector:
    app: "{{ prometheus_app_name }}"

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "{{ prometheus_app_name }}"
  labels:
    app: "{{ prometheus_app_name }}"
spec:
  to:
    kind: Service
    name: "{{ prometheus_app_name }}"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: "{{ prometheus_app_name }}"
  name: "{{ prometheus_app_name }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ prometheus_pvc_capacity }}"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ prometheus_app_name }}"
data:
  prometheus.yml: |
    global:
      external_labels:
        monitor: prometheus
    scrape_configs:
    - job_name: "{{ prometheus_scrape_job_name }}"
      tls_config:
        insecure_skip_verify: true
      honor_labels: true
      scrape_interval: 60s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets: {{ prometheus_target_hosts }}
