---
- name: Ensure that the required variables were found in the vars file
  fail:
    msg: "{{ item }} variable was not found in vars files"
  when: "{{ item }} is undefined"
  with_items:
    - namespace
    - kubeconfig
    - prometheus_target_hosts
    - prometheus_container_image
    - prometheus_app_name

- name: Delete the configmap so it can be recreated
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: absent
    namespace: "{{ namespace }}"
    verify_ssl: "no"
    api_version: v1
    kind: ConfigMap
    name: "{{ prometheus_app_name }}"

- name: Deploy the Prometheus objects to Openshift
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    namespace: "{{ namespace }}"
    verify_ssl: "no"
    definition: >-
      {{ lookup('template', 'main.yaml') }}
